/********************************************************************************
** Form generated from reading UI file 'controlcenter.ui'
**
** Created by: Qt User Interface Compiler version 5.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONTROLCENTER_H
#define UI_CONTROLCENTER_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ControlCenter
{
public:
    QLabel *label;
    QTabWidget *tab1;
    QWidget *tab;
    QListWidget *lw_desc;
    QPushButton *pb_clear;
    QGroupBox *groupBox;
    QLabel *label_4;
    QLineEdit *le_numIfaces;
    QSpinBox *sb_selectIf;
    QLabel *label_6;
    QLineEdit *le_numAlt;
    QCheckBox *cb_kerneldriver;
    QPushButton *pb_kerneldetach;
    QSpinBox *sb_selectAIf;
    QPushButton *pb_setIFace;
    QFrame *line;
    QPushButton *pb_setAltIf;
    QListWidget *lw_summ;
    QLabel *label_21;
    QWidget *tab_3;
    QTabWidget *tab2;
    QWidget *tab_4;
    QGroupBox *groupBox_2;
    QRadioButton *rb1_ram;
    QRadioButton *rb1_small;
    QRadioButton *rb1_large;
    QPushButton *pb1_selfile;
    QLabel *label_3;
    QLabel *label1_selfile;
    QListWidget *lw1_display;
    QPushButton *pb1_start;
    QPushButton *pb1_clear;
    QGroupBox *groupBox_3;
    QRadioButton *rb_internal;
    QRadioButton *rb_external;
    QWidget *tab_5;
    QListWidget *lw4_display;
    QLabel *label4_file;
    QPushButton *pb4_selfile;
    QPushButton *pb4_start;
    QPushButton *pb4_clear;
    QLabel *label_23;
    QGroupBox *groupBox_5;
    QRadioButton *rb4_ram;
    QRadioButton *rb4_i2c;
    QRadioButton *rb4_spi;
    QWidget *tab_6;
    QGroupBox *groupBox_4;
    QRadioButton *rb3_ramdl;
    QRadioButton *rb3_ramup;
    QRadioButton *rb3_eedl;
    QRadioButton *rb3_eeup;
    QRadioButton *rb3_getchip;
    QRadioButton *rb3_renum;
    QRadioButton *rb3_custom;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *le3_br;
    QLineEdit *le3_bm;
    QGroupBox *gb_dir;
    QRadioButton *rb3_out;
    QRadioButton *rb3_in;
    QLineEdit *le3_wval;
    QLineEdit *le3_wind;
    QLineEdit *le3_wlen;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *le3_out_hex;
    QPushButton *pb_execvc;
    QPushButton *pb3_selfile;
    QLabel *lab3_selfile;
    QLabel *label_26;
    QPushButton *pb3_dl;
    QListWidget *lw3;
    QPushButton *pb3;
    QLabel *label_22;
    QLineEdit *le3_out_ascii;
    QLabel *label_25;
    QLabel *label_30;
    QWidget *tab_2;
    QTabWidget *tabWidget;
    QWidget *tab_7;
    QComboBox *cb6_out;
    QComboBox *cb6_in;
    QGroupBox *groupBox_6;
    QRadioButton *rb6_constant;
    QRadioButton *rb6_random;
    QRadioButton *rb6_inc;
    QLineEdit *le6_value;
    QLabel *label_27;
    QLineEdit *le6_size;
    QCheckBox *cb6_loop;
    QLabel *label_28;
    QListWidget *lw6;
    QPushButton *pb6_clear;
    QPushButton *pb6_send;
    QPushButton *pb6_rcv;
    QLabel *label_31;
    QLabel *label_32;
    QGroupBox *groupBox_8;
    QLabel *label6_out;
    QLabel *label6_in;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_24;
    QLineEdit *le6_out_ascii;
    QLineEdit *le6_out_hex;
    QLabel *label_37;
    QLabel *label_29;
    QPushButton *pb6_selout;
    QPushButton *pb6_selin;
    QLineEdit *le6_outfile;
    QLineEdit *le6_infile;
    QListWidget *lw6_out;
    QLabel *label_75;
    QPushButton *pb6_clearhalt_out;
    QPushButton *pb6_clearhalt_in;
    QWidget *tab_8;
    QPushButton *pb7_clear;
    QPushButton *pb7_rcv;
    QComboBox *cb7_in;
    QPushButton *pb7_send;
    QComboBox *cb7_out;
    QLabel *label_71;
    QGroupBox *groupBox_16;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label7_totalout;
    QLabel *label_78;
    QLabel *label_80;
    QLabel *label7_totalin;
    QLabel *label7_rateout;
    QLabel *label7_ratein;
    QLabel *label7_pktsize_out;
    QLabel *label7_pktsize_in;
    QLabel *label_70;
    QFrame *line_2;
    QLabel *label7_pktsin;
    QLabel *label_79;
    QLabel *label7_pktsout;
    QLabel *label_81;
    QLabel *label7_dropped_out;
    QLabel *label7_dropped_in;
    QLabel *label_74;
    QListWidget *lw7_out;
    QListWidget *lw7_in;
    QLabel *label_66;
    QLabel *label_76;
    QLabel *label_77;
    QComboBox *cb7_numpkts;
    QGroupBox *groupBox_7;
    QRadioButton *rb7_enable;
    QRadioButton *rb7_disable;
    QPushButton *pb7_clearhalt_in;
    QPushButton *pb7_clearhalt_out;
    QWidget *tab_9;
    QComboBox *streamer_ep_sel;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *streamer_out_passcnt;
    QLabel *label_85;
    QLabel *label_86;
    QLabel *streamer_out_failcnt;
    QLabel *label_87;
    QLabel *streamer_out_perf;
    QPushButton *streamer_control_start;
    QComboBox *streamer_size_sel;
    QComboBox *streamer_queue_sel;
    QPushButton *streamer_control_stop;
    QLabel *label_2;
    QLabel *label_seldevice;
    QListWidget *listWidget;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_if;
    QLabel *label_aif;
    QPushButton *pb_reset;
    QLabel *label_20;
    QLabel *label_devtype;

    void setupUi(QWidget *ControlCenter)
    {
        if (ControlCenter->objectName().isEmpty())
            ControlCenter->setObjectName(QStringLiteral("ControlCenter"));
        ControlCenter->setWindowModality(Qt::NonModal);
        ControlCenter->resize(910, 660);
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(ControlCenter->sizePolicy().hasHeightForWidth());
        ControlCenter->setSizePolicy(sizePolicy);
        ControlCenter->setMinimumSize(QSize(910, 660));
        ControlCenter->setMaximumSize(QSize(910, 660));
        QFont font;
        font.setFamily(QStringLiteral("Noto Sans"));
        ControlCenter->setFont(font);
        QIcon icon;
        icon.addFile(QStringLiteral("cypress.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon.addFile(QStringLiteral("cypress.png"), QSize(), QIcon::Normal, QIcon::On);
        ControlCenter->setWindowIcon(icon);
        label = new QLabel(ControlCenter);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 30, 120, 20));
        tab1 = new QTabWidget(ControlCenter);
        tab1->setObjectName(QStringLiteral("tab1"));
        tab1->setGeometry(QRect(10, 155, 860, 485));
        tab1->setTabShape(QTabWidget::Rounded);
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        lw_desc = new QListWidget(tab);
        lw_desc->setObjectName(QStringLiteral("lw_desc"));
        lw_desc->setGeometry(QRect(435, 0, 410, 445));
        QFont font1;
        font1.setFamily(QStringLiteral("Noto Sans Mono"));
        lw_desc->setFont(font1);
        pb_clear = new QPushButton(tab);
        pb_clear->setObjectName(QStringLiteral("pb_clear"));
        pb_clear->setGeometry(QRect(370, 0, 65, 31));
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 0, 350, 120));
        groupBox->setAutoFillBackground(false);
        groupBox->setFlat(false);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 25, 137, 25));
        le_numIfaces = new QLineEdit(groupBox);
        le_numIfaces->setObjectName(QStringLiteral("le_numIfaces"));
        le_numIfaces->setGeometry(QRect(170, 25, 50, 25));
        le_numIfaces->setAlignment(Qt::AlignCenter);
        le_numIfaces->setReadOnly(true);
        sb_selectIf = new QSpinBox(groupBox);
        sb_selectIf->setObjectName(QStringLiteral("sb_selectIf"));
        sb_selectIf->setGeometry(QRect(230, 25, 40, 25));
        sb_selectIf->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 90, 160, 25));
        le_numAlt = new QLineEdit(groupBox);
        le_numAlt->setObjectName(QStringLiteral("le_numAlt"));
        le_numAlt->setGeometry(QRect(170, 90, 50, 25));
        le_numAlt->setAlignment(Qt::AlignCenter);
        le_numAlt->setReadOnly(true);
        cb_kerneldriver = new QCheckBox(groupBox);
        cb_kerneldriver->setObjectName(QStringLiteral("cb_kerneldriver"));
        cb_kerneldriver->setEnabled(true);
        cb_kerneldriver->setGeometry(QRect(10, 55, 140, 25));
        cb_kerneldriver->setCheckable(true);
        pb_kerneldetach = new QPushButton(groupBox);
        pb_kerneldetach->setObjectName(QStringLiteral("pb_kerneldetach"));
        pb_kerneldetach->setGeometry(QRect(170, 55, 50, 25));
        sb_selectAIf = new QSpinBox(groupBox);
        sb_selectAIf->setObjectName(QStringLiteral("sb_selectAIf"));
        sb_selectAIf->setGeometry(QRect(230, 90, 40, 25));
        sb_selectAIf->setAlignment(Qt::AlignCenter);
        pb_setIFace = new QPushButton(groupBox);
        pb_setIFace->setObjectName(QStringLiteral("pb_setIFace"));
        pb_setIFace->setGeometry(QRect(270, 25, 70, 25));
        line = new QFrame(groupBox);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(10, 80, 330, 10));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        pb_setAltIf = new QPushButton(groupBox);
        pb_setAltIf->setObjectName(QStringLiteral("pb_setAltIf"));
        pb_setAltIf->setGeometry(QRect(270, 90, 70, 25));
        lw_summ = new QListWidget(tab);
        lw_summ->setObjectName(QStringLiteral("lw_summ"));
        lw_summ->setGeometry(QRect(10, 150, 415, 295));
        lw_summ->setFont(font1);
        label_21 = new QLabel(tab);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 125, 415, 20));
        label_21->setFont(font1);
        tab1->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tab2 = new QTabWidget(tab_3);
        tab2->setObjectName(QStringLiteral("tab2"));
        tab2->setGeometry(QRect(10, 20, 835, 330));
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        groupBox_2 = new QGroupBox(tab_4);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(12, 20, 190, 100));
        rb1_ram = new QRadioButton(groupBox_2);
        rb1_ram->setObjectName(QStringLiteral("rb1_ram"));
        rb1_ram->setGeometry(QRect(10, 25, 170, 20));
        rb1_small = new QRadioButton(groupBox_2);
        rb1_small->setObjectName(QStringLiteral("rb1_small"));
        rb1_small->setGeometry(QRect(10, 50, 170, 20));
        rb1_large = new QRadioButton(groupBox_2);
        rb1_large->setObjectName(QStringLiteral("rb1_large"));
        rb1_large->setGeometry(QRect(10, 75, 170, 20));
        pb1_selfile = new QPushButton(tab_4);
        pb1_selfile->setObjectName(QStringLiteral("pb1_selfile"));
        pb1_selfile->setGeometry(QRect(110, 220, 110, 20));
        label_3 = new QLabel(tab_4);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(230, 5, 90, 30));
        label1_selfile = new QLabel(tab_4);
        label1_selfile->setObjectName(QStringLiteral("label1_selfile"));
        label1_selfile->setGeometry(QRect(330, 5, 490, 30));
        label1_selfile->setFrameShape(QFrame::Box);
        lw1_display = new QListWidget(tab_4);
        lw1_display->setObjectName(QStringLiteral("lw1_display"));
        lw1_display->setGeometry(QRect(230, 40, 590, 250));
        lw1_display->setFont(font1);
        pb1_start = new QPushButton(tab_4);
        pb1_start->setObjectName(QStringLiteral("pb1_start"));
        pb1_start->setGeometry(QRect(110, 245, 110, 20));
        pb1_clear = new QPushButton(tab_4);
        pb1_clear->setObjectName(QStringLiteral("pb1_clear"));
        pb1_clear->setGeometry(QRect(180, 270, 40, 20));
        groupBox_3 = new QGroupBox(tab_4);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(12, 130, 90, 80));
        rb_internal = new QRadioButton(groupBox_3);
        rb_internal->setObjectName(QStringLiteral("rb_internal"));
        rb_internal->setGeometry(QRect(5, 30, 80, 21));
        rb_external = new QRadioButton(groupBox_3);
        rb_external->setObjectName(QStringLiteral("rb_external"));
        rb_external->setGeometry(QRect(5, 50, 80, 20));
        tab2->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        lw4_display = new QListWidget(tab_5);
        lw4_display->setObjectName(QStringLiteral("lw4_display"));
        lw4_display->setGeometry(QRect(230, 40, 590, 250));
        lw4_display->setFont(font1);
        label4_file = new QLabel(tab_5);
        label4_file->setObjectName(QStringLiteral("label4_file"));
        label4_file->setGeometry(QRect(330, 5, 490, 30));
        label4_file->setFrameShape(QFrame::Box);
        pb4_selfile = new QPushButton(tab_5);
        pb4_selfile->setObjectName(QStringLiteral("pb4_selfile"));
        pb4_selfile->setGeometry(QRect(110, 220, 110, 20));
        pb4_start = new QPushButton(tab_5);
        pb4_start->setObjectName(QStringLiteral("pb4_start"));
        pb4_start->setGeometry(QRect(110, 245, 110, 20));
        pb4_clear = new QPushButton(tab_5);
        pb4_clear->setObjectName(QStringLiteral("pb4_clear"));
        pb4_clear->setGeometry(QRect(180, 270, 40, 20));
        label_23 = new QLabel(tab_5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(230, 5, 90, 30));
        groupBox_5 = new QGroupBox(tab_5);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(12, 20, 190, 100));
        rb4_ram = new QRadioButton(groupBox_5);
        rb4_ram->setObjectName(QStringLiteral("rb4_ram"));
        rb4_ram->setGeometry(QRect(10, 25, 170, 20));
        rb4_i2c = new QRadioButton(groupBox_5);
        rb4_i2c->setObjectName(QStringLiteral("rb4_i2c"));
        rb4_i2c->setGeometry(QRect(10, 50, 170, 20));
        rb4_spi = new QRadioButton(groupBox_5);
        rb4_spi->setObjectName(QStringLiteral("rb4_spi"));
        rb4_spi->setGeometry(QRect(10, 75, 170, 20));
        tab2->addTab(tab_5, QString());
        tab1->addTab(tab_3, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        groupBox_4 = new QGroupBox(tab_6);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 10, 170, 180));
        rb3_ramdl = new QRadioButton(groupBox_4);
        rb3_ramdl->setObjectName(QStringLiteral("rb3_ramdl"));
        rb3_ramdl->setGeometry(QRect(10, 30, 150, 20));
        rb3_ramup = new QRadioButton(groupBox_4);
        rb3_ramup->setObjectName(QStringLiteral("rb3_ramup"));
        rb3_ramup->setGeometry(QRect(10, 50, 150, 20));
        rb3_eedl = new QRadioButton(groupBox_4);
        rb3_eedl->setObjectName(QStringLiteral("rb3_eedl"));
        rb3_eedl->setGeometry(QRect(10, 70, 150, 20));
        rb3_eeup = new QRadioButton(groupBox_4);
        rb3_eeup->setObjectName(QStringLiteral("rb3_eeup"));
        rb3_eeup->setGeometry(QRect(10, 90, 150, 20));
        rb3_getchip = new QRadioButton(groupBox_4);
        rb3_getchip->setObjectName(QStringLiteral("rb3_getchip"));
        rb3_getchip->setGeometry(QRect(10, 110, 150, 20));
        rb3_renum = new QRadioButton(groupBox_4);
        rb3_renum->setObjectName(QStringLiteral("rb3_renum"));
        rb3_renum->setGeometry(QRect(10, 130, 150, 20));
        rb3_custom = new QRadioButton(groupBox_4);
        rb3_custom->setObjectName(QStringLiteral("rb3_custom"));
        rb3_custom->setGeometry(QRect(10, 150, 150, 20));
        label_10 = new QLabel(tab_6);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(315, 30, 70, 25));
        label_10->setFont(font);
        label_11 = new QLabel(tab_6);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(190, 30, 110, 25));
        QFont font2;
        font2.setFamily(QStringLiteral("Noto Sans "));
        font2.setPointSize(10);
        label_11->setFont(font2);
        label_12 = new QLabel(tab_6);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(410, 30, 60, 25));
        label_12->setFont(font);
        label_13 = new QLabel(tab_6);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(505, 30, 60, 25));
        label_14 = new QLabel(tab_6);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(600, 30, 70, 25));
        le3_br = new QLineEdit(tab_6);
        le3_br->setObjectName(QStringLiteral("le3_br"));
        le3_br->setGeometry(QRect(315, 60, 60, 25));
        le3_bm = new QLineEdit(tab_6);
        le3_bm->setObjectName(QStringLiteral("le3_bm"));
        le3_bm->setGeometry(QRect(190, 60, 90, 25));
        gb_dir = new QGroupBox(tab_6);
        gb_dir->setObjectName(QStringLiteral("gb_dir"));
        gb_dir->setGeometry(QRect(190, 100, 90, 70));
        rb3_out = new QRadioButton(gb_dir);
        rb3_out->setObjectName(QStringLiteral("rb3_out"));
        rb3_out->setGeometry(QRect(10, 25, 70, 20));
        rb3_in = new QRadioButton(gb_dir);
        rb3_in->setObjectName(QStringLiteral("rb3_in"));
        rb3_in->setGeometry(QRect(10, 45, 70, 20));
        le3_wval = new QLineEdit(tab_6);
        le3_wval->setObjectName(QStringLiteral("le3_wval"));
        le3_wval->setGeometry(QRect(410, 60, 60, 25));
        le3_wind = new QLineEdit(tab_6);
        le3_wind->setObjectName(QStringLiteral("le3_wind"));
        le3_wind->setGeometry(QRect(505, 60, 60, 25));
        le3_wlen = new QLineEdit(tab_6);
        le3_wlen->setObjectName(QStringLiteral("le3_wlen"));
        le3_wlen->setGeometry(QRect(600, 60, 60, 25));
        le3_wlen->setMaxLength(5);
        label_15 = new QLabel(tab_6);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(315, 10, 80, 20));
        QFont font3;
        font3.setPointSize(8);
        label_15->setFont(font3);
        label_16 = new QLabel(tab_6);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(190, 10, 80, 20));
        label_16->setFont(font3);
        label_17 = new QLabel(tab_6);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(410, 10, 90, 20));
        label_17->setFont(font3);
        label_18 = new QLabel(tab_6);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(505, 10, 90, 20));
        label_18->setFont(font3);
        label_19 = new QLabel(tab_6);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(600, 10, 90, 20));
        label_19->setFont(font3);
        le3_out_hex = new QLineEdit(tab_6);
        le3_out_hex->setObjectName(QStringLiteral("le3_out_hex"));
        le3_out_hex->setGeometry(QRect(350, 170, 410, 25));
        le3_out_hex->setMaxLength(64);
        pb_execvc = new QPushButton(tab_6);
        pb_execvc->setObjectName(QStringLiteral("pb_execvc"));
        pb_execvc->setGeometry(QRect(680, 60, 160, 30));
        QFont font4;
        font4.setPointSize(11);
        pb_execvc->setFont(font4);
        pb3_selfile = new QPushButton(tab_6);
        pb3_selfile->setObjectName(QStringLiteral("pb3_selfile"));
        pb3_selfile->setGeometry(QRect(290, 110, 50, 30));
        lab3_selfile = new QLabel(tab_6);
        lab3_selfile->setObjectName(QStringLiteral("lab3_selfile"));
        lab3_selfile->setGeometry(QRect(350, 110, 410, 30));
        lab3_selfile->setFrameShape(QFrame::Box);
        label_26 = new QLabel(tab_6);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(350, 90, 251, 16));
        pb3_dl = new QPushButton(tab_6);
        pb3_dl->setObjectName(QStringLiteral("pb3_dl"));
        pb3_dl->setGeometry(QRect(770, 110, 70, 30));
        lw3 = new QListWidget(tab_6);
        lw3->setObjectName(QStringLiteral("lw3"));
        lw3->setGeometry(QRect(10, 240, 750, 200));
        lw3->setFont(font1);
        pb3 = new QPushButton(tab_6);
        pb3->setObjectName(QStringLiteral("pb3"));
        pb3->setGeometry(QRect(770, 240, 70, 30));
        label_22 = new QLabel(tab_6);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 220, 141, 16));
        le3_out_ascii = new QLineEdit(tab_6);
        le3_out_ascii->setObjectName(QStringLiteral("le3_out_ascii"));
        le3_out_ascii->setGeometry(QRect(350, 200, 410, 25));
        le3_out_ascii->setMaxLength(64);
        label_25 = new QLabel(tab_6);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(220, 170, 120, 25));
        label_25->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_30 = new QLabel(tab_6);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(220, 200, 120, 25));
        label_30->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tab1->addTab(tab_6, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tabWidget = new QTabWidget(tab_2);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 835, 430));
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        cb6_out = new QComboBox(tab_7);
        cb6_out->setObjectName(QStringLiteral("cb6_out"));
        cb6_out->setGeometry(QRect(50, 30, 100, 30));
        cb6_in = new QComboBox(tab_7);
        cb6_in->setObjectName(QStringLiteral("cb6_in"));
        cb6_in->setGeometry(QRect(180, 30, 100, 30));
        groupBox_6 = new QGroupBox(tab_7);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(440, 20, 121, 81));
        rb6_constant = new QRadioButton(groupBox_6);
        rb6_constant->setObjectName(QStringLiteral("rb6_constant"));
        rb6_constant->setGeometry(QRect(10, 20, 106, 20));
        rb6_random = new QRadioButton(groupBox_6);
        rb6_random->setObjectName(QStringLiteral("rb6_random"));
        rb6_random->setGeometry(QRect(10, 40, 106, 20));
        rb6_inc = new QRadioButton(groupBox_6);
        rb6_inc->setObjectName(QStringLiteral("rb6_inc"));
        rb6_inc->setGeometry(QRect(10, 60, 121, 20));
        le6_value = new QLineEdit(tab_7);
        le6_value->setObjectName(QStringLiteral("le6_value"));
        le6_value->setGeometry(QRect(580, 40, 81, 25));
        le6_value->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_27 = new QLabel(tab_7);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(580, 20, 81, 16));
        le6_size = new QLineEdit(tab_7);
        le6_size->setObjectName(QStringLiteral("le6_size"));
        le6_size->setGeometry(QRect(670, 40, 81, 25));
        le6_size->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cb6_loop = new QCheckBox(tab_7);
        cb6_loop->setObjectName(QStringLiteral("cb6_loop"));
        cb6_loop->setGeometry(QRect(308, 90, 90, 30));
        label_28 = new QLabel(tab_7);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(670, 20, 81, 16));
        lw6 = new QListWidget(tab_7);
        lw6->setObjectName(QStringLiteral("lw6"));
        lw6->setGeometry(QRect(420, 230, 400, 155));
        lw6->setFont(font1);
        pb6_clear = new QPushButton(tab_7);
        pb6_clear->setObjectName(QStringLiteral("pb6_clear"));
        pb6_clear->setGeometry(QRect(780, 200, 40, 30));
        pb6_send = new QPushButton(tab_7);
        pb6_send->setObjectName(QStringLiteral("pb6_send"));
        pb6_send->setGeometry(QRect(50, 90, 100, 30));
        pb6_rcv = new QPushButton(tab_7);
        pb6_rcv->setObjectName(QStringLiteral("pb6_rcv"));
        pb6_rcv->setGeometry(QRect(180, 90, 100, 30));
        label_31 = new QLabel(tab_7);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(50, 5, 100, 20));
        label_31->setAlignment(Qt::AlignCenter);
        label_32 = new QLabel(tab_7);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(180, 5, 100, 20));
        label_32->setAlignment(Qt::AlignCenter);
        groupBox_8 = new QGroupBox(tab_7);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(660, 70, 160, 120));
        label6_out = new QLabel(groupBox_8);
        label6_out->setObjectName(QStringLiteral("label6_out"));
        label6_out->setGeometry(QRect(80, 26, 71, 20));
        label6_out->setFrameShape(QFrame::Box);
        label6_out->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label6_in = new QLabel(groupBox_8);
        label6_in->setObjectName(QStringLiteral("label6_in"));
        label6_in->setGeometry(QRect(80, 56, 71, 20));
        label6_in->setFrameShape(QFrame::Box);
        label6_in->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_35 = new QLabel(groupBox_8);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 30, 59, 15));
        label_36 = new QLabel(groupBox_8);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 60, 59, 15));
        label_24 = new QLabel(tab_7);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(9, 210, 50, 20));
        label_24->setFont(font3);
        le6_out_ascii = new QLineEdit(tab_7);
        le6_out_ascii->setObjectName(QStringLiteral("le6_out_ascii"));
        le6_out_ascii->setGeometry(QRect(160, 170, 431, 25));
        le6_out_ascii->setMaxLength(64);
        le6_out_hex = new QLineEdit(tab_7);
        le6_out_hex->setObjectName(QStringLiteral("le6_out_hex"));
        le6_out_hex->setGeometry(QRect(160, 140, 431, 25));
        le6_out_hex->setMaxLength(64);
        label_37 = new QLabel(tab_7);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(60, 170, 101, 16));
        label_29 = new QLabel(tab_7);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(60, 140, 101, 16));
        pb6_selout = new QPushButton(tab_7);
        pb6_selout->setObjectName(QStringLiteral("pb6_selout"));
        pb6_selout->setGeometry(QRect(100, 200, 50, 25));
        pb6_selin = new QPushButton(tab_7);
        pb6_selin->setObjectName(QStringLiteral("pb6_selin"));
        pb6_selin->setGeometry(QRect(469, 200, 50, 25));
        le6_outfile = new QLineEdit(tab_7);
        le6_outfile->setObjectName(QStringLiteral("le6_outfile"));
        le6_outfile->setGeometry(QRect(160, 200, 250, 25));
        le6_outfile->setReadOnly(true);
        le6_infile = new QLineEdit(tab_7);
        le6_infile->setObjectName(QStringLiteral("le6_infile"));
        le6_infile->setGeometry(QRect(528, 200, 240, 25));
        le6_infile->setReadOnly(true);
        lw6_out = new QListWidget(tab_7);
        lw6_out->setObjectName(QStringLiteral("lw6_out"));
        lw6_out->setGeometry(QRect(10, 230, 400, 155));
        lw6_out->setFont(font1);
        label_75 = new QLabel(tab_7);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(420, 210, 50, 20));
        label_75->setFont(font3);
        pb6_clearhalt_out = new QPushButton(tab_7);
        pb6_clearhalt_out->setObjectName(QStringLiteral("pb6_clearhalt_out"));
        pb6_clearhalt_out->setGeometry(QRect(50, 60, 100, 20));
        pb6_clearhalt_out->setFont(font3);
        pb6_clearhalt_in = new QPushButton(tab_7);
        pb6_clearhalt_in->setObjectName(QStringLiteral("pb6_clearhalt_in"));
        pb6_clearhalt_in->setGeometry(QRect(180, 60, 100, 20));
        pb6_clearhalt_in->setFont(font3);
        tabWidget->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        pb7_clear = new QPushButton(tab_8);
        pb7_clear->setObjectName(QStringLiteral("pb7_clear"));
        pb7_clear->setGeometry(QRect(780, 200, 40, 30));
        pb7_rcv = new QPushButton(tab_8);
        pb7_rcv->setObjectName(QStringLiteral("pb7_rcv"));
        pb7_rcv->setGeometry(QRect(180, 90, 100, 30));
        cb7_in = new QComboBox(tab_8);
        cb7_in->setObjectName(QStringLiteral("cb7_in"));
        cb7_in->setGeometry(QRect(180, 30, 100, 30));
        pb7_send = new QPushButton(tab_8);
        pb7_send->setObjectName(QStringLiteral("pb7_send"));
        pb7_send->setGeometry(QRect(50, 90, 100, 30));
        cb7_out = new QComboBox(tab_8);
        cb7_out->setObjectName(QStringLiteral("cb7_out"));
        cb7_out->setGeometry(QRect(50, 30, 100, 30));
        label_71 = new QLabel(tab_8);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(50, 5, 100, 20));
        label_71->setAlignment(Qt::AlignCenter);
        groupBox_16 = new QGroupBox(tab_8);
        groupBox_16->setObjectName(QStringLiteral("groupBox_16"));
        groupBox_16->setGeometry(QRect(470, 5, 350, 200));
        groupBox_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        groupBox_16->setFlat(false);
        label_72 = new QLabel(groupBox_16);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(140, 30, 90, 20));
        label_72->setAlignment(Qt::AlignCenter);
        label_73 = new QLabel(groupBox_16);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(240, 30, 90, 20));
        label_73->setAlignment(Qt::AlignCenter);
        label7_totalout = new QLabel(groupBox_16);
        label7_totalout->setObjectName(QStringLiteral("label7_totalout"));
        label7_totalout->setGeometry(QRect(140, 85, 90, 20));
        label7_totalout->setFont(font1);
        label7_totalout->setFrameShape(QFrame::Box);
        label7_totalout->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_78 = new QLabel(groupBox_16);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(15, 85, 121, 21));
        label_80 = new QLabel(groupBox_16);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(15, 170, 81, 16));
        label7_totalin = new QLabel(groupBox_16);
        label7_totalin->setObjectName(QStringLiteral("label7_totalin"));
        label7_totalin->setGeometry(QRect(240, 85, 90, 20));
        label7_totalin->setFont(font1);
        label7_totalin->setFrameShape(QFrame::Box);
        label7_totalin->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_rateout = new QLabel(groupBox_16);
        label7_rateout->setObjectName(QStringLiteral("label7_rateout"));
        label7_rateout->setGeometry(QRect(140, 170, 90, 20));
        label7_rateout->setFont(font1);
        label7_rateout->setFrameShape(QFrame::Box);
        label7_rateout->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_ratein = new QLabel(groupBox_16);
        label7_ratein->setObjectName(QStringLiteral("label7_ratein"));
        label7_ratein->setGeometry(QRect(240, 170, 90, 20));
        label7_ratein->setFont(font1);
        label7_ratein->setFrameShape(QFrame::Box);
        label7_ratein->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_pktsize_out = new QLabel(groupBox_16);
        label7_pktsize_out->setObjectName(QStringLiteral("label7_pktsize_out"));
        label7_pktsize_out->setGeometry(QRect(140, 50, 90, 21));
        label7_pktsize_out->setFont(font1);
        label7_pktsize_out->setFrameShape(QFrame::Box);
        label7_pktsize_out->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_pktsize_in = new QLabel(groupBox_16);
        label7_pktsize_in->setObjectName(QStringLiteral("label7_pktsize_in"));
        label7_pktsize_in->setGeometry(QRect(240, 50, 90, 21));
        label7_pktsize_in->setFont(font1);
        label7_pktsize_in->setFrameShape(QFrame::Box);
        label7_pktsize_in->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_70 = new QLabel(groupBox_16);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(15, 50, 100, 20));
        QFont font5;
        font5.setPointSize(9);
        label_70->setFont(font5);
        line_2 = new QFrame(groupBox_16);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(15, 70, 315, 16));
        line_2->setLineWidth(2);
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label7_pktsin = new QLabel(groupBox_16);
        label7_pktsin->setObjectName(QStringLiteral("label7_pktsin"));
        label7_pktsin->setGeometry(QRect(240, 110, 90, 21));
        label7_pktsin->setFont(font1);
        label7_pktsin->setFrameShape(QFrame::Box);
        label7_pktsin->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_79 = new QLabel(groupBox_16);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(15, 115, 126, 16));
        label7_pktsout = new QLabel(groupBox_16);
        label7_pktsout->setObjectName(QStringLiteral("label7_pktsout"));
        label7_pktsout->setGeometry(QRect(140, 110, 90, 20));
        label7_pktsout->setFont(font1);
        label7_pktsout->setFrameShape(QFrame::Box);
        label7_pktsout->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_81 = new QLabel(groupBox_16);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(15, 145, 126, 16));
        label7_dropped_out = new QLabel(groupBox_16);
        label7_dropped_out->setObjectName(QStringLiteral("label7_dropped_out"));
        label7_dropped_out->setGeometry(QRect(140, 140, 90, 20));
        label7_dropped_out->setFont(font1);
        label7_dropped_out->setFrameShape(QFrame::Box);
        label7_dropped_out->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_dropped_in = new QLabel(groupBox_16);
        label7_dropped_in->setObjectName(QStringLiteral("label7_dropped_in"));
        label7_dropped_in->setGeometry(QRect(240, 140, 90, 20));
        label7_dropped_in->setFont(font1);
        label7_dropped_in->setFrameShape(QFrame::Box);
        label7_dropped_in->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_74 = new QLabel(tab_8);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(180, 5, 100, 20));
        label_74->setAlignment(Qt::AlignCenter);
        lw7_out = new QListWidget(tab_8);
        lw7_out->setObjectName(QStringLiteral("lw7_out"));
        lw7_out->setGeometry(QRect(10, 230, 400, 155));
        lw7_out->setFont(font1);
        lw7_in = new QListWidget(tab_8);
        lw7_in->setObjectName(QStringLiteral("lw7_in"));
        lw7_in->setGeometry(QRect(420, 230, 400, 155));
        lw7_in->setFont(font1);
        label_66 = new QLabel(tab_8);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(10, 210, 80, 20));
        label_66->setFont(font3);
        label_76 = new QLabel(tab_8);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(430, 210, 80, 20));
        label_76->setFont(font3);
        label_77 = new QLabel(tab_8);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(310, 5, 100, 20));
        label_77->setAlignment(Qt::AlignCenter);
        cb7_numpkts = new QComboBox(tab_8);
        cb7_numpkts->setObjectName(QStringLiteral("cb7_numpkts"));
        cb7_numpkts->setGeometry(QRect(310, 30, 100, 30));
        cb7_numpkts->setFont(font1);
        groupBox_7 = new QGroupBox(tab_8);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(340, 130, 120, 75));
        rb7_enable = new QRadioButton(groupBox_7);
        rb7_enable->setObjectName(QStringLiteral("rb7_enable"));
        rb7_enable->setGeometry(QRect(10, 25, 100, 20));
        rb7_disable = new QRadioButton(groupBox_7);
        rb7_disable->setObjectName(QStringLiteral("rb7_disable"));
        rb7_disable->setGeometry(QRect(10, 50, 100, 20));
        pb7_clearhalt_in = new QPushButton(tab_8);
        pb7_clearhalt_in->setObjectName(QStringLiteral("pb7_clearhalt_in"));
        pb7_clearhalt_in->setGeometry(QRect(180, 60, 100, 20));
        pb7_clearhalt_in->setFont(font3);
        pb7_clearhalt_out = new QPushButton(tab_8);
        pb7_clearhalt_out->setObjectName(QStringLiteral("pb7_clearhalt_out"));
        pb7_clearhalt_out->setGeometry(QRect(50, 60, 100, 20));
        pb7_clearhalt_out->setFont(font3);
        tabWidget->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        streamer_ep_sel = new QComboBox(tab_9);
        streamer_ep_sel->setObjectName(QStringLiteral("streamer_ep_sel"));
        streamer_ep_sel->setGeometry(QRect(140, 20, 201, 25));
        label_82 = new QLabel(tab_9);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(20, 20, 71, 31));
        label_83 = new QLabel(tab_9);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(20, 60, 111, 31));
        label_84 = new QLabel(tab_9);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(20, 100, 111, 31));
        streamer_out_passcnt = new QLabel(tab_9);
        streamer_out_passcnt->setObjectName(QStringLiteral("streamer_out_passcnt"));
        streamer_out_passcnt->setGeometry(QRect(620, 20, 141, 20));
        streamer_out_passcnt->setFont(font1);
        streamer_out_passcnt->setFrameShape(QFrame::Box);
        streamer_out_passcnt->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_85 = new QLabel(tab_9);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(530, 20, 81, 21));
        label_85->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_86 = new QLabel(tab_9);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(530, 60, 81, 21));
        label_86->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        streamer_out_failcnt = new QLabel(tab_9);
        streamer_out_failcnt->setObjectName(QStringLiteral("streamer_out_failcnt"));
        streamer_out_failcnt->setGeometry(QRect(620, 60, 141, 20));
        streamer_out_failcnt->setFont(font1);
        streamer_out_failcnt->setFrameShape(QFrame::Box);
        streamer_out_failcnt->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_87 = new QLabel(tab_9);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(460, 100, 151, 21));
        label_87->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        streamer_out_perf = new QLabel(tab_9);
        streamer_out_perf->setObjectName(QStringLiteral("streamer_out_perf"));
        streamer_out_perf->setGeometry(QRect(620, 100, 141, 20));
        streamer_out_perf->setFont(font1);
        streamer_out_perf->setFrameShape(QFrame::Box);
        streamer_out_perf->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        streamer_control_start = new QPushButton(tab_9);
        streamer_control_start->setObjectName(QStringLiteral("streamer_control_start"));
        streamer_control_start->setGeometry(QRect(270, 160, 111, 27));
        streamer_size_sel = new QComboBox(tab_9);
        streamer_size_sel->setObjectName(QStringLiteral("streamer_size_sel"));
        streamer_size_sel->setGeometry(QRect(140, 60, 201, 25));
        streamer_queue_sel = new QComboBox(tab_9);
        streamer_queue_sel->setObjectName(QStringLiteral("streamer_queue_sel"));
        streamer_queue_sel->setGeometry(QRect(140, 100, 201, 25));
        streamer_control_stop = new QPushButton(tab_9);
        streamer_control_stop->setObjectName(QStringLiteral("streamer_control_stop"));
        streamer_control_stop->setGeometry(QRect(480, 160, 111, 27));
        tabWidget->addTab(tab_9, QString());
        tab1->addTab(tab_2, QString());
        label_2 = new QLabel(ControlCenter);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(370, 30, 120, 20));
        label_seldevice = new QLabel(ControlCenter);
        label_seldevice->setObjectName(QStringLiteral("label_seldevice"));
        label_seldevice->setGeometry(QRect(370, 50, 350, 30));
        QFont font6;
        font6.setUnderline(false);
        label_seldevice->setFont(font6);
        label_seldevice->setAutoFillBackground(false);
        label_seldevice->setFrameShape(QFrame::StyledPanel);
        label_seldevice->setLineWidth(2);
        label_seldevice->setMidLineWidth(0);
        listWidget = new QListWidget(ControlCenter);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(10, 50, 335, 100));
        label_8 = new QLabel(ControlCenter);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(370, 85, 130, 25));
        label_9 = new QLabel(ControlCenter);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(370, 120, 150, 25));
        label_if = new QLabel(ControlCenter);
        label_if->setObjectName(QStringLiteral("label_if"));
        label_if->setGeometry(QRect(510, 85, 30, 25));
        label_if->setAutoFillBackground(false);
        label_if->setFrameShape(QFrame::Box);
        label_if->setAlignment(Qt::AlignCenter);
        label_aif = new QLabel(ControlCenter);
        label_aif->setObjectName(QStringLiteral("label_aif"));
        label_aif->setGeometry(QRect(510, 120, 30, 25));
        label_aif->setFrameShape(QFrame::Box);
        label_aif->setAlignment(Qt::AlignCenter);
        pb_reset = new QPushButton(ControlCenter);
        pb_reset->setObjectName(QStringLiteral("pb_reset"));
        pb_reset->setGeometry(QRect(750, 155, 120, 30));
        label_20 = new QLabel(ControlCenter);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(580, 85, 91, 25));
        label_devtype = new QLabel(ControlCenter);
        label_devtype->setObjectName(QStringLiteral("label_devtype"));
        label_devtype->setGeometry(QRect(670, 85, 50, 25));
        label_devtype->setFrameShape(QFrame::Box);
        label_devtype->setAlignment(Qt::AlignCenter);
        QWidget::setTabOrder(rb3_custom, rb3_out);
        QWidget::setTabOrder(rb3_out, rb3_in);
        QWidget::setTabOrder(rb3_in, le3_bm);
        QWidget::setTabOrder(le3_bm, le3_br);
        QWidget::setTabOrder(le3_br, le3_wval);
        QWidget::setTabOrder(le3_wval, le3_wind);
        QWidget::setTabOrder(le3_wind, le3_wlen);
        QWidget::setTabOrder(le3_wlen, le3_out_ascii);
        QWidget::setTabOrder(le3_out_ascii, le3_out_hex);
        QWidget::setTabOrder(le3_out_hex, pb_execvc);
        QWidget::setTabOrder(pb_execvc, pb_setIFace);
        QWidget::setTabOrder(pb_setIFace, pb_setAltIf);
        QWidget::setTabOrder(pb_setAltIf, tab2);
        QWidget::setTabOrder(tab2, rb1_ram);
        QWidget::setTabOrder(rb1_ram, rb1_small);
        QWidget::setTabOrder(rb1_small, rb1_large);
        QWidget::setTabOrder(rb1_large, pb1_selfile);
        QWidget::setTabOrder(pb1_selfile, lw1_display);
        QWidget::setTabOrder(lw1_display, pb1_start);
        QWidget::setTabOrder(pb1_start, pb1_clear);
        QWidget::setTabOrder(pb1_clear, rb_internal);
        QWidget::setTabOrder(rb_internal, rb_external);
        QWidget::setTabOrder(rb_external, lw4_display);
        QWidget::setTabOrder(lw4_display, pb4_selfile);
        QWidget::setTabOrder(pb4_selfile, pb4_start);
        QWidget::setTabOrder(pb4_start, pb4_clear);
        QWidget::setTabOrder(pb4_clear, rb4_ram);
        QWidget::setTabOrder(rb4_ram, rb4_i2c);
        QWidget::setTabOrder(rb4_i2c, rb4_spi);
        QWidget::setTabOrder(rb4_spi, rb3_ramdl);
        QWidget::setTabOrder(rb3_ramdl, rb3_ramup);
        QWidget::setTabOrder(rb3_ramup, rb3_eedl);
        QWidget::setTabOrder(rb3_eedl, rb3_eeup);
        QWidget::setTabOrder(rb3_eeup, rb3_getchip);
        QWidget::setTabOrder(rb3_getchip, rb3_renum);
        QWidget::setTabOrder(rb3_renum, tab1);
        QWidget::setTabOrder(tab1, pb_clear);
        QWidget::setTabOrder(pb_clear, lw_desc);
        QWidget::setTabOrder(lw_desc, listWidget);
        QWidget::setTabOrder(listWidget, pb_reset);
        QWidget::setTabOrder(pb_reset, le_numIfaces);
        QWidget::setTabOrder(le_numIfaces, sb_selectIf);
        QWidget::setTabOrder(sb_selectIf, le_numAlt);
        QWidget::setTabOrder(le_numAlt, pb_kerneldetach);
        QWidget::setTabOrder(pb_kerneldetach, sb_selectAIf);
        QWidget::setTabOrder(sb_selectAIf, pb3_selfile);
        QWidget::setTabOrder(pb3_selfile, pb3_dl);
        QWidget::setTabOrder(pb3_dl, lw3);
        QWidget::setTabOrder(lw3, pb3);
        QWidget::setTabOrder(pb3, cb_kerneldriver);
        QWidget::setTabOrder(cb_kerneldriver, tabWidget);
        QWidget::setTabOrder(tabWidget, cb6_out);
        QWidget::setTabOrder(cb6_out, cb6_in);
        QWidget::setTabOrder(cb6_in, rb6_constant);
        QWidget::setTabOrder(rb6_constant, rb6_random);
        QWidget::setTabOrder(rb6_random, rb6_inc);
        QWidget::setTabOrder(rb6_inc, le6_value);
        QWidget::setTabOrder(le6_value, le6_size);
        QWidget::setTabOrder(le6_size, cb6_loop);
        QWidget::setTabOrder(cb6_loop, lw6);
        QWidget::setTabOrder(lw6, pb6_clear);
        QWidget::setTabOrder(pb6_clear, pb6_send);
        QWidget::setTabOrder(pb6_send, pb6_rcv);
        QWidget::setTabOrder(pb6_rcv, le6_out_ascii);
        QWidget::setTabOrder(le6_out_ascii, le6_out_hex);

        retranslateUi(ControlCenter);
        QObject::connect(pb_clear, SIGNAL(clicked()), lw_desc, SLOT(clear()));
        QObject::connect(listWidget, SIGNAL(currentTextChanged(QString)), label_seldevice, SLOT(setText(QString)));
        QObject::connect(pb1_clear, SIGNAL(clicked()), lw1_display, SLOT(clear()));
        QObject::connect(rb3_ramdl, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(rb3_ramup, SIGNAL(clicked()), rb3_in, SLOT(click()));
        QObject::connect(rb3_eedl, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(rb3_eeup, SIGNAL(clicked()), rb3_in, SLOT(click()));
        QObject::connect(rb3_getchip, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(rb3_renum, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(pb3, SIGNAL(clicked()), lw3, SLOT(clear()));
        QObject::connect(pb3, SIGNAL(clicked()), le3_out_hex, SLOT(clear()));
        QObject::connect(pb3, SIGNAL(clicked()), le3_out_ascii, SLOT(clear()));

        tab1->setCurrentIndex(0);
        tab2->setCurrentIndex(0);
        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ControlCenter);
    } // setupUi

    void retranslateUi(QWidget *ControlCenter)
    {
        ControlCenter->setWindowTitle(QApplication::translate("ControlCenter", "CyUSB Suite for Linux", 0));
        label->setText(QApplication::translate("ControlCenter", "Detected Devices", 0));
        pb_clear->setText(QApplication::translate("ControlCenter", "Clear", 0));
        groupBox->setTitle(QApplication::translate("ControlCenter", "Interface", 0));
        label_4->setText(QApplication::translate("ControlCenter", "Num. of Interfaces", 0));
        label_6->setText(QApplication::translate("ControlCenter", "Num. of Alternate Ifaces", 0));
        cb_kerneldriver->setText(QApplication::translate("ControlCenter", "Interface Claimed", 0));
        pb_kerneldetach->setText(QApplication::translate("ControlCenter", "Detach", 0));
        pb_setIFace->setText(QApplication::translate("ControlCenter", "Set IF", 0));
        pb_setAltIf->setText(QApplication::translate("ControlCenter", "Set Alt. IF", 0));
        label_21->setText(QApplication::translate("ControlCenter", " If#    Alt    EP#    I/O    Type   MaxPS  Interval", 0));
        tab1->setTabText(tab1->indexOf(tab), QApplication::translate("ControlCenter", "Descriptors", 0));
        groupBox_2->setTitle(QApplication::translate("ControlCenter", "Download to", 0));
        rb1_ram->setText(QApplication::translate("ControlCenter", "RAM", 0));
        rb1_small->setText(QApplication::translate("ControlCenter", "Small EEPROM", 0));
        rb1_large->setText(QApplication::translate("ControlCenter", "&Large EEPROM (64KB)", 0));
        pb1_selfile->setText(QApplication::translate("ControlCenter", "Select File", 0));
        label_3->setText(QApplication::translate("ControlCenter", "Selected File", 0));
        label1_selfile->setText(QString());
        pb1_start->setText(QApplication::translate("ControlCenter", "Start Download", 0));
        pb1_clear->setText(QApplication::translate("ControlCenter", "Clear", 0));
        groupBox_3->setTitle(QApplication::translate("ControlCenter", "Which RAM", 0));
        rb_internal->setText(QApplication::translate("ControlCenter", "Internal", 0));
        rb_external->setText(QApplication::translate("ControlCenter", "E&xternal", 0));
        tab2->setTabText(tab2->indexOf(tab_4), QApplication::translate("ControlCenter", "FX2", 0));
        label4_file->setText(QString());
        pb4_selfile->setText(QApplication::translate("ControlCenter", "Select File", 0));
        pb4_start->setText(QApplication::translate("ControlCenter", "Start Download", 0));
        pb4_clear->setText(QApplication::translate("ControlCenter", "Clear", 0));
        label_23->setText(QApplication::translate("ControlCenter", "Selected File", 0));
        groupBox_5->setTitle(QApplication::translate("ControlCenter", "Download to", 0));
        rb4_ram->setText(QApplication::translate("ControlCenter", "RAM", 0));
        rb4_i2c->setText(QApplication::translate("ControlCenter", "I&2C EEPROM", 0));
        rb4_spi->setText(QApplication::translate("ControlCenter", "SPI F&lash", 0));
        tab2->setTabText(tab2->indexOf(tab_5), QApplication::translate("ControlCenter", "FX3", 0));
        tab1->setTabText(tab1->indexOf(tab_3), QApplication::translate("ControlCenter", "Program", 0));
        groupBox_4->setTitle(QApplication::translate("ControlCenter", "Command", 0));
        rb3_ramdl->setText(QApplication::translate("ControlCenter", "RAM (E&xt.) Download", 0));
        rb3_ramup->setText(QApplication::translate("ControlCenter", "RAM (Ext.) Upload", 0));
        rb3_eedl->setText(QApplication::translate("ControlCenter", "EEPROM Down&load", 0));
        rb3_eeup->setText(QApplication::translate("ControlCenter", "EEPROM &Upload", 0));
        rb3_getchip->setText(QApplication::translate("ControlCenter", "Ge&t Chip Revision", 0));
        rb3_renum->setText(QApplication::translate("ControlCenter", "Renumerate", 0));
        rb3_custom->setText(QApplication::translate("ControlCenter", "Custom", 0));
        label_10->setText(QApplication::translate("ControlCenter", "bRequest", 0));
        label_11->setText(QApplication::translate("ControlCenter", "bmRequestType", 0));
        label_12->setText(QApplication::translate("ControlCenter", "wValue", 0));
        label_13->setText(QApplication::translate("ControlCenter", "wIndex", 0));
        label_14->setText(QApplication::translate("ControlCenter", "wLength", 0));
        gb_dir->setTitle(QApplication::translate("ControlCenter", "Direction", 0));
        rb3_out->setText(QApplication::translate("ControlCenter", "OUT", 0));
        rb3_in->setText(QApplication::translate("ControlCenter", "IN", 0));
        label_15->setText(QApplication::translate("ControlCenter", "SETUPDAT[1]", 0));
        label_16->setText(QApplication::translate("ControlCenter", "SETUPDAT[0]", 0));
        label_17->setText(QApplication::translate("ControlCenter", "SETUPDAT[2,3]", 0));
        label_18->setText(QApplication::translate("ControlCenter", "SETUPDAT[4,5]", 0));
        label_19->setText(QApplication::translate("ControlCenter", "SETUPDAT[6,7]", 0));
        pb_execvc->setText(QApplication::translate("ControlCenter", "Execute Command", 0));
        pb3_selfile->setText(QApplication::translate("ControlCenter", "Select", 0));
        lab3_selfile->setText(QString());
        label_26->setText(QApplication::translate("ControlCenter", "Select firmware file to download", 0));
        pb3_dl->setText(QApplication::translate("ControlCenter", "Download", 0));
        pb3->setText(QApplication::translate("ControlCenter", "Clear", 0));
        label_22->setText(QApplication::translate("ControlCenter", "DATA / Status", 0));
        label_25->setText(QApplication::translate("ControlCenter", "Data-Out HEX", 0));
        label_30->setText(QApplication::translate("ControlCenter", "Data-Out ASCII", 0));
        tab1->setTabText(tab1->indexOf(tab_6), QApplication::translate("ControlCenter", "Vendor Extensions", 0));
        groupBox_6->setTitle(QApplication::translate("ControlCenter", "Data Pattern", 0));
        rb6_constant->setText(QApplication::translate("ControlCenter", "Constant", 0));
        rb6_random->setText(QApplication::translate("ControlCenter", "Random", 0));
        rb6_inc->setText(QApplication::translate("ControlCenter", "Incrementing", 0));
        le6_value->setInputMask(QApplication::translate("ControlCenter", "HH", 0));
        label_27->setText(QApplication::translate("ControlCenter", "Value (HEX)", 0));
        cb6_loop->setText(QApplication::translate("ControlCenter", "Loopback", 0));
        label_28->setText(QApplication::translate("ControlCenter", "Size (bytes)", 0));
        pb6_clear->setText(QApplication::translate("ControlCenter", "Clear", 0));
        pb6_send->setText(QApplication::translate("ControlCenter", "SEND", 0));
        pb6_rcv->setText(QApplication::translate("ControlCenter", "RECEIVE", 0));
        label_31->setText(QApplication::translate("ControlCenter", "Endpoint OUT", 0));
        label_32->setText(QApplication::translate("ControlCenter", "Endpoint IN", 0));
        groupBox_8->setTitle(QApplication::translate("ControlCenter", "Transfer Statistics", 0));
        label6_out->setText(QString());
        label6_in->setText(QString());
        label_35->setText(QApplication::translate("ControlCenter", "Data Out", 0));
        label_36->setText(QApplication::translate("ControlCenter", "Data In", 0));
        label_24->setText(QApplication::translate("ControlCenter", "Data Out", 0));
        label_37->setText(QApplication::translate("ControlCenter", "Data-Out ASCII", 0));
        label_29->setText(QApplication::translate("ControlCenter", "Data-Out HEX", 0));
        pb6_selout->setText(QApplication::translate("ControlCenter", "out-file", 0));
        pb6_selin->setText(QApplication::translate("ControlCenter", "in-file", 0));
        label_75->setText(QApplication::translate("ControlCenter", "Data In", 0));
        pb6_clearhalt_out->setText(QApplication::translate("ControlCenter", "Clear Halt", 0));
        pb6_clearhalt_in->setText(QApplication::translate("ControlCenter", "Clear Halt", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QApplication::translate("ControlCenter", "Bulk", 0));
        pb7_clear->setText(QApplication::translate("ControlCenter", "Clear", 0));
        pb7_rcv->setText(QApplication::translate("ControlCenter", "RECEIVE", 0));
        pb7_send->setText(QApplication::translate("ControlCenter", "SEND", 0));
        label_71->setText(QApplication::translate("ControlCenter", "Endpoint OUT", 0));
        groupBox_16->setTitle(QApplication::translate("ControlCenter", "Transfer Statistics", 0));
        label_72->setText(QApplication::translate("ControlCenter", "Data Out", 0));
        label_73->setText(QApplication::translate("ControlCenter", "Data In", 0));
        label7_totalout->setText(QString());
        label_78->setText(QApplication::translate("ControlCenter", "Total Packets", 0));
        label_80->setText(QApplication::translate("ControlCenter", " Rate (KB/s)", 0));
        label7_totalin->setText(QString());
        label7_rateout->setText(QString());
        label7_ratein->setText(QString());
        label7_pktsize_out->setText(QString());
        label7_pktsize_in->setText(QString());
        label_70->setText(QApplication::translate("ControlCenter", "Max Pkt. Size", 0));
        label7_pktsin->setText(QString());
        label_79->setText(QApplication::translate("ControlCenter", "Packets - Success", 0));
        label7_pktsout->setText(QString());
        label_81->setText(QApplication::translate("ControlCenter", "Packets - Failed", 0));
        label7_dropped_out->setText(QString());
        label7_dropped_in->setText(QString());
        label_74->setText(QApplication::translate("ControlCenter", "Endpoint IN", 0));
        label_66->setText(QApplication::translate("ControlCenter", "Data Out", 0));
        label_76->setText(QApplication::translate("ControlCenter", "Data In", 0));
        label_77->setText(QApplication::translate("ControlCenter", "Num Pkts", 0));
        groupBox_7->setTitle(QApplication::translate("ControlCenter", "Display Dump", 0));
        rb7_enable->setText(QApplication::translate("ControlCenter", "Enab&le", 0));
        rb7_disable->setText(QApplication::translate("ControlCenter", "Disable", 0));
        pb7_clearhalt_in->setText(QApplication::translate("ControlCenter", "Clear Halt", 0));
        pb7_clearhalt_out->setText(QApplication::translate("ControlCenter", "Clear Halt", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_8), QApplication::translate("ControlCenter", "Isochronous", 0));
        label_82->setText(QApplication::translate("ControlCenter", "Endpoint", 0));
        label_83->setText(QApplication::translate("ControlCenter", "Transfer Size", 0));
        label_84->setText(QApplication::translate("ControlCenter", "Queue Depth", 0));
        streamer_out_passcnt->setText(QString());
        label_85->setText(QApplication::translate("ControlCenter", "Pass Count", 0));
        label_86->setText(QApplication::translate("ControlCenter", "Fail Count", 0));
        streamer_out_failcnt->setText(QString());
        label_87->setText(QApplication::translate("ControlCenter", "Performance (KBps)", 0));
        streamer_out_perf->setText(QString());
        streamer_control_start->setText(QApplication::translate("ControlCenter", "Start", 0));
        streamer_control_stop->setText(QApplication::translate("ControlCenter", "Stop", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_9), QApplication::translate("ControlCenter", "Streamer", 0));
        tab1->setTabText(tab1->indexOf(tab_2), QApplication::translate("ControlCenter", " Data Transfers", 0));
        label_2->setText(QApplication::translate("ControlCenter", "Selected Device", 0));
        label_seldevice->setText(QString());
        label_8->setText(QApplication::translate("ControlCenter", "Selected Interface", 0));
        label_9->setText(QApplication::translate("ControlCenter", "Selected Alt Interface", 0));
        label_if->setText(QString());
        label_aif->setText(QString());
        pb_reset->setText(QApplication::translate("ControlCenter", "Reset Device", 0));
        label_20->setText(QApplication::translate("ControlCenter", "Device Type", 0));
        label_devtype->setText(QApplication::translate("ControlCenter", "FX2", 0));
    } // retranslateUi

};

namespace Ui {
    class ControlCenter: public Ui_ControlCenter {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONTROLCENTER_H
